SeatableNetCoreSdk/samples/WebApplicationSample/Controllers/RowController.cs
using Microsoft.AspNetCore.Mvc;
using JackieSoft.SeatableNetCoreSdk.Domain;
using JackieSoft.SeatableNetCoreSdk.DTableServer;
using System.Collections.Generic;
using System.Threading.Tasks;
using WebApplicationSample.Models;

namespace WebApplicationSample.Controllers
{
    public class RowController : Controller
    {
        private readonly IRowService _rowService;
        public RowController(IRowService rowService)
        {
            this._rowService = rowService;
        }
        public async Task<IActionResult> Index()
        {
            await GetListAsync();
            return View();
        }
        private async Task<SeatableRowListResponseModel> GetListAsync()
        {
            var titleList = new List<string> {
             "_id",
             "工厂",
             "产品",
             "损失率"
            };

            var result = await this._rowService.ListAsync(new JackieSoft.SeatableNetCoreSdk.Domain.SeatableRowListModel
            {
                DTableUuid = "a13abaf8-b79b-427d-802d-303cc1b60f6e",
                TableName = "n8n-table",
                Token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MzIwMzI5MTIsImR0YWJsZV91dWlkIjoiYTEzYWJhZjgtYjc5Yi00MjdkLTgwMmQtMzAzY2MxYjYwZjZlIiwidXNlcm5hbWUiOiI5OTA4ZDAyMTEwZWQ0MDNjOWM0N2JhMTg2OWVjOTE3YUBhdXRoLmxvY2FsIiwiaWRfaW5fb3JnIjoiIiwicGVybWlzc2lvbiI6InJ3In0.VpgzKB7q1hpbE5G4XMPXj56cUj4ceOVM4wMR736qikE"
            });
            ViewData["data"] = result;
            ViewData["title"] = titleList;
            return result;
        }
        public async Task<IActionResult> Update(RowUpdateViewModel model)
        {
            if (!string.IsNullOrEmpty(model.Value))
            {
                var result = await this._rowService.UpdateAsync(new JackieSoft.SeatableNetCoreSdk.Domain.SeatableRowUpdateModel
                {
                    DTableUuid = "a13abaf8-b79b-427d-802d-303cc1b60f6e",
                    Row = new SeatableUpdateRow
                    {
                        RowId = model.RowId,
                        TableName = model.TableName,
                        Row = new Dictionary<string, object> {
                        {model.Field,model.Value}
                       }
                    },
                    Token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MzIwMzI5MTIsImR0YWJsZV91dWlkIjoiYTEzYWJhZjgtYjc5Yi00MjdkLTgwMmQtMzAzY2MxYjYwZjZlIiwidXNlcm5hbWUiOiI5OTA4ZDAyMTEwZWQ0MDNjOWM0N2JhMTg2OWVjOTE3YUBhdXRoLmxvY2FsIiwiaWRfaW5fb3JnIjoiIiwicGVybWlzc2lvbiI6InJ3In0.VpgzKB7q1hpbE5G4XMPXj56cUj4ceOVM4wMR736qikE"
                });
                ViewData["success"] = result["success"];
            }
            return View();
        }
        public async Task<IActionResult> Append(RowAppendViewModel model)
        {
            if (!string.IsNullOrEmpty(model.Factory))
            {
                var result = await this._rowService.AppendAsync(new JackieSoft.SeatableNetCoreSdk.Domain.SeatableRowAppendModel
                {
                    DTableUuid = "a13abaf8-b79b-427d-802d-303cc1b60f6e",
                    TableName = model.TableName,
                    Row = new Dictionary<string, object> {
                        {"工厂",model.Factory},
                        {"产品",model.Product},
                        {"损失率",model.Rate}
                       },
                    Token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MzIwMzI5MTIsImR0YWJsZV91dWlkIjoiYTEzYWJhZjgtYjc5Yi00MjdkLTgwMmQtMzAzY2MxYjYwZjZlIiwidXNlcm5hbWUiOiI5OTA4ZDAyMTEwZWQ0MDNjOWM0N2JhMTg2OWVjOTE3YUBhdXRoLmxvY2FsIiwiaWRfaW5fb3JnIjoiIiwicGVybWlzc2lvbiI6InJ3In0.VpgzKB7q1hpbE5G4XMPXj56cUj4ceOVM4wMR736qikE"
                });
                ViewData["data"] = result;
            }
            else
            {
                ViewData["data"] = new Dictionary<string, object> {
                    {"_id",""}

                };
            }
            return View();
        }
        public async Task<IActionResult> Insert(RowInsertViewModel model)
        {
            if (!string.IsNullOrEmpty(model.Factory))
            {
                var result = await this._rowService.InsertAsync(new JackieSoft.SeatableNetCoreSdk.Domain.SeatableRowInsertModel
                {
                    DTableUuid = "a13abaf8-b79b-427d-802d-303cc1b60f6e",
                    TableName = model.TableName,
                    AnchorRowId = model.AnchorRowId,
                    Row = new Dictionary<string, object> {
                        {"工厂",model.Factory},
                        {"产品",model.Product},
                        {"损失率",model.Rate}
                       },
                    Token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MzIwMzI5MTIsImR0YWJsZV91dWlkIjoiYTEzYWJhZjgtYjc5Yi00MjdkLTgwMmQtMzAzY2MxYjYwZjZlIiwidXNlcm5hbWUiOiI5OTA4ZDAyMTEwZWQ0MDNjOWM0N2JhMTg2OWVjOTE3YUBhdXRoLmxvY2FsIiwiaWRfaW5fb3JnIjoiIiwicGVybWlzc2lvbiI6InJ3In0.VpgzKB7q1hpbE5G4XMPXj56cUj4ceOVM4wMR736qikE"
                });
                ViewData["data"] = result;
            }
            else
            {
                ViewData["data"] = new Dictionary<string, object> {
                    {"_id",""}

                };
            }
            return View();
        }
        public async Task<IActionResult> BatchAppend(RowBatchAppendViewModel model)
        {
            if (!string.IsNullOrEmpty(model.Factory))
            {
                var rows = new List<Dictionary<string, object>>();
                for (int i = 0; i < model.Count; i++)
                {
                    rows.Add(new Dictionary<string, object> {
                        {"工厂",model.Factory+"-"+i},
                        {"产品",model.Product},
                        {"损失率",model.Rate}
                       });
                }
                var result = await this._rowService.BatchAppendAsync(new JackieSoft.SeatableNetCoreSdk.Domain.SeatableRowBatchAppendModel
                {
                    DTableUuid = "a13abaf8-b79b-427d-802d-303cc1b60f6e",
                    TableName = model.TableName,
                    Rows = rows,
                    Token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MzIwMzI5MTIsImR0YWJsZV91dWlkIjoiYTEzYWJhZjgtYjc5Yi00MjdkLTgwMmQtMzAzY2MxYjYwZjZlIiwidXNlcm5hbWUiOiI5OTA4ZDAyMTEwZWQ0MDNjOWM0N2JhMTg2OWVjOTE3YUBhdXRoLmxvY2FsIiwiaWRfaW5fb3JnIjoiIiwicGVybWlzc2lvbiI6InJ3In0.VpgzKB7q1hpbE5G4XMPXj56cUj4ceOVM4wMR736qikE"
                });
                ViewData["data"] = result;
            }
            else
            {
                ViewData["data"] = new Dictionary<string, object> {
                    {"inserted_row_count","0"}

                };
            }
            return View();
        }
        public async Task<IActionResult> BatchUpdate(RowUpdateViewModel model)
        {
            if (!string.IsNullOrEmpty(model.TableName))
            {
                var item = await GetListAsync();
                var list = new List<SeatableRowBatchUpdateItem>();
                for (int i = 0; i < item.Rows.Count; i++)
                {
                    list.Add(new SeatableRowBatchUpdateItem
                    {
                        RowId = item.Rows[i]["_id"].ToString(),
                        Row = new Dictionary<string, object> {
                         { "工厂",item.Rows[i]["工厂"]+"_"+i },
                         { "产品",item.Rows[i]["产品"] },
                         { "损失率",item.Rows[i]["损失率"] },
                     }
                    });
                }
                var result = await this._rowService.BatchUpdateAsync(new JackieSoft.SeatableNetCoreSdk.Domain.SeatableRowBatchUpdateModel
                {
                    DTableUuid = "a13abaf8-b79b-427d-802d-303cc1b60f6e",
                    TableName = model.TableName,
                    Rows = list,
                    Token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MzIwMzI5MTIsImR0YWJsZV91dWlkIjoiYTEzYWJhZjgtYjc5Yi00MjdkLTgwMmQtMzAzY2MxYjYwZjZlIiwidXNlcm5hbWUiOiI5OTA4ZDAyMTEwZWQ0MDNjOWM0N2JhMTg2OWVjOTE3YUBhdXRoLmxvY2FsIiwiaWRfaW5fb3JnIjoiIiwicGVybWlzc2lvbiI6InJ3In0.VpgzKB7q1hpbE5G4XMPXj56cUj4ceOVM4wMR736qikE"
                });
                ViewData["result"] = result;
                await GetListAsync();
            }
            else
            {
                await GetListAsync();
                ViewData["result"] = new Dictionary<string, object> {
                    {"success","0"}

                };
            }
            return View();
        }
        public async Task<IActionResult> GetRow(RowGetViewModel model)
        {
            if (!string.IsNullOrEmpty(model.RowId))
            {
                var result = await this._rowService.GetAsync(new JackieSoft.SeatableNetCoreSdk.Domain.SeatableRowGetModel
                {
                    DTableUuid = "a13abaf8-b79b-427d-802d-303cc1b60f6e",
                    RowId = model.RowId,
                    TableId = model.TableId,
                    Token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MzIwMzI5MTIsImR0YWJsZV91dWlkIjoiYTEzYWJhZjgtYjc5Yi00MjdkLTgwMmQtMzAzY2MxYjYwZjZlIiwidXNlcm5hbWUiOiI5OTA4ZDAyMTEwZWQ0MDNjOWM0N2JhMTg2OWVjOTE3YUBhdXRoLmxvY2FsIiwiaWRfaW5fb3JnIjoiIiwicGVybWlzc2lvbiI6InJ3In0.VpgzKB7q1hpbE5G4XMPXj56cUj4ceOVM4wMR736qikE"
                });
                ViewData["data"] = result;
            }
            else
            {
                ViewData["data"] = new Dictionary<string, object> {
                    {"_id",""}

                };
            }
            return View();
        }
        public async Task<IActionResult> Lock(RowLockViewModel model)
        {
            await GetListAsync();
            if (model.RowIds != null)
            {
                var ids = model.RowIds.Split(',', System.StringSplitOptions.RemoveEmptyEntries);
                var idList = new List<string>();
                foreach (var id in ids)
                {
                    idList.Add(id);
                }

SeatableNetCoreSdk/samples/WebApplicationSample/Views/Row/Append.cshtml
@model RowAppendViewModel
@{
    ViewData["Title"] = "追加一行";
    var data = ViewData["data"] as Dictionary<string, object>;
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="Row" asp-action="Append" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Factory">工厂</label>
                <input type="text" class="form-control" asp-for="Factory" value="" />
            </div>
            <div class="form-group">
                <label asp-for="Product">产品</label>
                <input type="text" class="form-control" asp-for="Product" value="" />
            </div>
            <div class="form-group">
                <label asp-for="Rate">损失率</label>
                <input type="text" class="form-control" asp-for="Rate" value="" />
            </div>
            <div class="form-group">
                <label asp-for="UUID">dtable-uuid</label>
                <input type="text" class="form-control" asp-for="UUID" value="" />
            </div>

            <div class="form-group">
                <label asp-for="TableName">表名</label>
                <input type="text" class="form-control" asp-for="TableName" value="n8n-table" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>  结果:<span>@data["_id"]</span>
        </form>
        <hr />
    </div>
</div>

SeatableNetCoreSdk/samples/WebApplicationSample/Views/Row/BatchAppend.cshtml
@model RowBatchAppendViewModel
@{
    ViewData["Title"] = "追加多行";
    var data = ViewData["data"] as Dictionary<string, object>;
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="Row" asp-action="BatchAppend" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Factory">工厂</label>
                <input type="text" class="form-control" asp-for="Factory" value="" />
            </div>
            <div class="form-group">
                <label asp-for="Product">产品</label>
                <input type="text" class="form-control" asp-for="Product" value="" />
            </div>
            <div class="form-group">
                <label asp-for="Rate">损失率</label>
                <input type="text" class="form-control" asp-for="Rate" value="" />
            </div>
            <div class="form-group">
                <label asp-for="Count">条数</label>
                <input type="number" class="form-control" asp-for="Count" value="3" />
            </div>
            <div class="form-group">
                <label asp-for="UUID">dtable-uuid</label>
                <input type="text" class="form-control" asp-for="UUID" value="" />
            </div>

            <div class="form-group">
                <label asp-for="TableName">表名</label>
                <input type="text" class="form-control" asp-for="TableName" value="n8n-table" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>  结果:<span>@data["inserted_row_count"]</span>
        </form>
        <hr />
    </div>
</div>

SeatableNetCoreSdk/samples/WebApplicationSample/Views/Row/BatchDelete.cshtml
@using JackieSoft.SeatableNetCoreSdk.Domain
@model RowLockViewModel
@{
    ViewData["Title_"] = "删除多行";
    var model = ViewData["data"] as SeatableRowListResponseModel;
    var titles = ViewData["title"] as List<string>;
    var result = ViewData["result"] as Dictionary<string, object>;
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title_"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    @foreach (var title in titles)
                    {
                        <th>@title</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var row in model.Rows)
                {
                    <tr>
                        @foreach (var title in titles)
                        {
                            <td>@row[title]</td>
                        }
                    </tr>
                }
            </tbody>
        </table>
        <form asp-controller="Row" asp-action="BatchDelete" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TableName"></label>
                <input type="text" class="form-control" asp-for="TableName" value="" />
            </div>
            <div class="form-group">
                <label asp-for="RowIds"></label>
                <input type="text" class="form-control" asp-for="RowIds" value="" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>  结果:@result["deleted_rows"]
        </form>
        <hr />
    </div>
</div>

SeatableNetCoreSdk/samples/WebApplicationSample/Views/Row/BatchUpdate.cshtml
@using JackieSoft.SeatableNetCoreSdk.Domain
@model RowBatchUpdateViewModel

@{
    ViewData["Title_"] = "更新多行";
    var model = ViewData["data"] as SeatableRowListResponseModel;
    var titles = ViewData["title"] as List<string>;
    var result = ViewData["result"] as Dictionary<string, object>;
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title_"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="Row" asp-action="BatchUpdate" method="post">
            <div class="form-group">
                <label asp-for="TableName">表名</label>
                <input type="text" class="form-control" asp-for="TableName" value="n8n-table" />
            </div>
            <table class="table">
                <thead>
                    <tr>
                        @foreach (var title in titles)
                        {
                            <th>@title</th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach (var row in model.Rows)
                    {
                        <tr>
                            @foreach (var title in titles)
                            {
                                <td>@row[title]</td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
            <button type="submit" class="btn btn-primary">提交请求</button>  结果:@result["success"]
        </form>
    </div>
</div>

SeatableNetCoreSdk/samples/WebApplicationSample/Views/Row/Delete.cshtml
@using JackieSoft.SeatableNetCoreSdk.Domain
@model RowLockViewModel
@{
    ViewData["Title_"] = "删除一行";
    var model = ViewData["data"] as SeatableRowListResponseModel;
    var titles = ViewData["title"] as List<string>;
    var result = ViewData["result"] as Dictionary<string, object>;
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title_"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    @foreach (var title in titles)
                    {
                        <th>@title</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var row in model.Rows)
                {
                    <tr>
                        @foreach (var title in titles)
                        {
                            <td>@row[title]</td>
                        }
                    </tr>
                }
            </tbody>
        </table>
        <form asp-controller="Row" asp-action="Delete" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TableName"></label>
                <input type="text" class="form-control" asp-for="TableName" value="" />
            </div>
            <div class="form-group">
                <label asp-for="RowIds"></label>
                <input type="text" class="form-control" asp-for="RowIds" value="" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>  结果:@result["deleted_rows"]
        </form>
        <hr />
    </div>
</div>

SeatableNetCoreSdk/samples/WebApplicationSample/Views/Row/GetRow.cshtml
@model RowGetViewModel
@{
    ViewData["Title"] = "查询一行";
    var result = ViewData["data"] as Dictionary<string, object>;
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="Row" asp-action="GetRow" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TableId"></label>
                <input type="text" class="form-control" asp-for="TableId" value="" />
            </div>
            <div class="form-group">
                <label asp-for="RowId"></label>
                <input type="text" class="form-control" asp-for="RowId" value="" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>  结果:@result["_id"]
        </form>
        <hr />
    </div>
</div>

SeatableNetCoreSdk/samples/WebApplicationSample/Views/Row/Index.cshtml
@using JackieSoft.SeatableNetCoreSdk.Domain
<table>
    <tr>
        <td><a class="nav-link text-dark" asp-area="" asp-controller="Row" asp-action="Update">更新</a></td>
        <td><a class="nav-link text-dark" asp-area="" asp-controller="Row" asp-action="Append">追加</a></td>
        <td><a class="nav-link text-dark" asp-area="" asp-controller="Row" asp-action="Insert">插入</a></td>
        <td><a class="nav-link text-dark" asp-area="" asp-controller="Row" asp-action="BatchAppend">追加多行</a></td>
        <td><a class="nav-link text-dark" asp-area="" asp-controller="Row" asp-action="BatchUpdate">更新多行</a></td>
        <td><a class="nav-link text-dark" asp-area="" asp-controller="Row" asp-action="GetRow">查询一行</a></td>
        <td><a class="nav-link text-dark" asp-area="" asp-controller="Row" asp-action="Lock">锁定行</a></td>
        <td><a class="nav-link text-dark" asp-area="" asp-controller="Row" asp-action="UnLock">解锁行</a></td>
        <td><a class="nav-link text-dark" asp-area="" asp-controller="Row" asp-action="Delete">删除一行</a></td>
        <td><a class="nav-link text-dark" asp-area="" asp-controller="Row" asp-action="BatchDelete">删除多行</a></td>
    </tr>
</table>
@model SeatableRowListResponseModel


<br />
@{
    var model = ViewData["data"] as SeatableRowListResponseModel;
    var titles = ViewData["title"] as List<string>;
}
<table class="table">
    <thead>
        <tr>
            @foreach (var title in titles)
            {
                <th>@title</th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var row in model.Rows)
        {
            <tr>
                @foreach (var title in titles)
                {
                    <th>@row[title]</th>
                }
            </tr>
        }
    </tbody>
</table>

SeatableNetCoreSdk/samples/WebApplicationSample/Views/Row/Insert.cshtml
@model RowInsertViewModel
@{
    ViewData["Title"] = "插入一行";
    var data = ViewData["data"] as Dictionary<string, object>;
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="Row" asp-action="Insert" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Factory">工厂</label>
                <input type="text" class="form-control" asp-for="Factory" value="" />
            </div>
            <div class="form-group">
                <label asp-for="Product">产品</label>
                <input type="text" class="form-control" asp-for="Product" value="" />
            </div>
            <div class="form-group">
                <label asp-for="Rate">损失率</label>
                <input type="text" class="form-control" asp-for="Rate" value="" />
            </div>
            <div class="form-group">
                <label asp-for="UUID">dtable-uuid</label>
                <input type="text" class="form-control" asp-for="UUID" value="" />
            </div>
            <div class="form-group">
                <label asp-for="AnchorRowId">anchor_row_id</label>
                <input type="text" class="form-control" asp-for="AnchorRowId" value="" />
            </div>
            <div class="form-group">
                <label asp-for="TableName">表名</label>
                <input type="text" class="form-control" asp-for="TableName" value="n8n-table" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>  结果:<span>@data["_id"]</span>
        </form>
        <hr />
    </div>
</div>

SeatableNetCoreSdk/samples/WebApplicationSample/Views/Row/Lock.cshtml
@using JackieSoft.SeatableNetCoreSdk.Domain
@model RowLockViewModel
@{
    ViewData["Title_"] = "锁定行";
    var model = ViewData["data"] as SeatableRowListResponseModel;
    var titles = ViewData["title"] as List<string>;
    var result = ViewData["result"] as Dictionary<string, object>;
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title_"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    @foreach (var title in titles)
                    {
                        <th>@title</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var row in model.Rows)
                {
                    <tr>
                        @foreach (var title in titles)
                        {
                            <td>@row[title]</td>
                        }
                    </tr>
                }
            </tbody>
        </table>
        <form asp-controller="Row" asp-action="Lock" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TableName"></label>
                <input type="text" class="form-control" asp-for="TableName" value="" />
            </div>
            <div class="form-group">
                <label asp-for="RowIds"></label>
                <input type="text" class="form-control" asp-for="RowIds" value="" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>  结果:@result["success"]
        </form>
        <hr />
    </div>
</div>

SeatableNetCoreSdk/samples/WebApplicationSample/Views/Row/UnLock.cshtml
@using JackieSoft.SeatableNetCoreSdk.Domain
@model RowLockViewModel
@{
    ViewData["Title_"] = "解锁行";
    var model = ViewData["data"] as SeatableRowListResponseModel;
    var titles = ViewData["title"] as List<string>;
    var result = ViewData["result"] as Dictionary<string, object>;
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title_"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    @foreach (var title in titles)
                    {
                        <th>@title</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var row in model.Rows)
                {
                    <tr>
                        @foreach (var title in titles)
                        {
                            <td>@row[title]</td>
                        }
                    </tr>
                }
            </tbody>
        </table>
        <form asp-controller="Row" asp-action="UnLock" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TableName"></label>
                <input type="text" class="form-control" asp-for="TableName" value="" />
            </div>
            <div class="form-group">
                <label asp-for="RowIds"></label>
                <input type="text" class="form-control" asp-for="RowIds" value="" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>  结果:@result["success"]
        </form>
        <hr />
    </div>
</div>

SeatableNetCoreSdk/samples/WebApplicationSample/Views/Row/Update.cshtml
@model RowUpdateViewModel
@{
    ViewData["Title"] = "更新一行";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="Row" asp-action="Update" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Field">字段名</label>
                <input type="text" class="form-control" asp-for="Field" value="" />
            </div>
            <div class="form-group">
                <label asp-for="Value">字段值</label>
                <input type="text" class="form-control" asp-for="Value" value="" />
            </div>
            <div class="form-group">
                <label asp-for="TableName"></label>
                <input type="text" class="form-control" asp-for="TableName" value="" />
            </div>
            <div class="form-group">
                <label asp-for="RowId"></label>
                <input type="text" class="form-control" asp-for="RowId" value="" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>  结果:@ViewData["success"]
        </form>
        <hr />
    </div>
</div>