SeatableNetCoreSdk/samples/WebApplicationSample/Controllers/AuthTokenController.cs
using Microsoft.AspNetCore.Mvc;
using JackieSoft.SeatableNetCoreSdk.Auth;
using JackieSoft.SeatableNetCoreSdk.Domain;
using System.Threading.Tasks;
using WebApplicationSample.Models;

namespace WebApplicationSample.Controllers
{
    public class AuthTokenController : Controller
    {
        private readonly IAuthTokenService _authTokenService;

        public AuthTokenController(IAuthTokenService authTokenService)
        {
            this._authTokenService = authTokenService;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AuthToken(AuthViewModel viewModel)
        {
            var model = new SeatableAuthModel
            {
                UserName = viewModel.UserName,
                Password = viewModel.Password
            };
            var result = await this._authTokenService.AuthTokenAsync(model);
            ViewData["response"] = result.Token;
            return View();
        }        
    }
}

SeatableNetCoreSdk/samples/WebApplicationSample/Views/AuthToken/AuthToken.cshtml
<form class="form-horizontal">
    <div class="form-group">
        <label>Response:</label>
        <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
    </div>
</form>

SeatableNetCoreSdk/samples/WebApplicationSample/Views/AuthToken/Index.cshtml
@model AuthViewModel
@{
    ViewData["Title"] = "全局登录";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">        
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="AuthToken" asp-action="AuthToken">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName"></label>
                <input type="text" class="form-control" asp-for="UserName" value="" />
            </div>
            <div class="form-group">
                <label asp-for="Password"></label>
                <input type="password" class="form-control" asp-for="Password" value="" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />       
    </div>
</div>